name: "Wind River eLxr 12"
type: "deb"  # Repository type: rpm or deb
baseURL: "https://mirror.elxr.dev/elxr/dists/aria/main"
pkgPrefix: "https://mirror.elxr.dev/elxr/"
releaseFile: "https://mirror.elxr.dev/elxr/dists/aria/Release"
releaseSign: "https://mirror.elxr.dev/elxr/dists/aria/Release.gpg"
pbGPGKey: "https://mirror.elxr.dev/elxr/public.gpg"
gpgCheck: true
repoGPGCheck: true
enabled: true
component: "main"  # Repository component/section identifier
buildPath: "./builds/elxr12"