image:
  name: minimal-os-image-elxr
  version: "12.0.0"

target:
  os: wind-river-elxr # Target OS name
  dist: elxr12 # Target OS distribution
  arch: x86_64 # Target OS architecture
  imageType: img # Image type, valid value: [raw, iso].

systemConfig:
  name: ISO_Initrd
  description: Default yml configuration for iso initrd image

  bootloader:
    bootType: efi # (efi or legacy)
    provider: grub # (grub for efi and legacy mode, or systemd-boot for efi mode)

  packages:
    - linux-image-amd64
    - ca-certificates
    - vim
    - sudo
    - net-tools
    - openssh-client
    - openssh-server
    - procps
    - less
    - dbus
    - policykit-1
    - curl
    - wget
    - uefi-ext4
    - systemd-resolved
    - cloud-guest-utils
    - xterm
    - dracut
    - systemd-boot
    - grub2
    - grub-pc-bin
    - grub-efi-amd64-bin

  kernel:
    name: kernel
    version: "6.12"
    cmdline: "quiet splash console=ttyS0,115200 console=tty0 loglevel=7"