repositories:
  - name: "noble"
    type: "deb"  # Repository type: rpm or deb
    baseURL: "http://archive.ubuntu.com/ubuntu"
    pkgPrefix: "http://archive.ubuntu.com/ubuntu"
    releaseFile: "http://archive.ubuntu.com/ubuntu/dists/noble/Release"
    releaseSign: "http://archive.ubuntu.com/ubuntu/dists/noble/Release.gpg"
    pbGPGKey: "/usr/share/keyrings/ubuntu-archive-keyring.gpg"
    gpgCheck: true
    repoGPGCheck: true
    enabled: true
    component: "main restricted universe multiverse"  # Repository component/section identifier
    buildPath: "./builds/nanas24/main"  # Will be replaced with temp_dir/builds/nanas24/main at runtime
  - name: "noble-security"
    type: "deb"
    baseURL: "http://security.ubuntu.com/ubuntu"
    pkgPrefix: "http://security.ubuntu.com/ubuntu"
    releaseFile: "http://security.ubuntu.com/ubuntu/dists/noble-security/Release"
    releaseSign: "http://security.ubuntu.com/ubuntu/dists/noble-security/Release.gpg"
    pbGPGKey: "/usr/share/keyrings/ubuntu-archive-keyring.gpg"
    gpgCheck: true
    repoGPGCheck: true
    enabled: true
    component: "main restricted universe multiverse"
    buildPath: "./builds/nanas24/security"  # Will be replaced with temp_dir/builds/nanas24/security at runtime
  - name: "noble-updates"
    type: "deb"
    baseURL: "http://archive.ubuntu.com/ubuntu"
    pkgPrefix: "http://archive.ubuntu.com/ubuntu"
    releaseFile: "http://archive.ubuntu.com/ubuntu/dists/noble-updates/Release"
    releaseSign: "http://archive.ubuntu.com/ubuntu/dists/noble-updates/Release.gpg"
    pbGPGKey: "/usr/share/keyrings/ubuntu-archive-keyring.gpg"
    gpgCheck: true
    repoGPGCheck: true
    enabled: true
    component: "main restricted universe multiverse"
    buildPath: "./builds/nanas24/updates"  # Will be replaced with temp_dir/builds/nanas24/updates at runtime